Updated to use centralised CI and standard version format for changelog
zepben/pp-translator pull request #18
Opened 2022-10-28 04:34 UTC by alourie

Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

2022-10-28 04:34 UTC, ryanjcoleman commented
Task linked: [OPS-158 Standardise changelog format across all repos](https://app.clickup.com/t/6929263/OPS-158)

2022-10-30 22:41 UTC, kgreav requested changes
Can you please add the hotfix/LTS branch workflows

2022-10-30 22:41 UTC, kgreav commented on changelog.md
> +## [0.4.0]
Does this need the  `- UNRELEASED`?

2022-10-31 12:41 UTC, alourie commented on changelog.md
> +## [0.4.0]
yea, :facepalm:

2022-11-01 10:29 UTC, kgreav approved these changes

2022-11-01 10:29 UTC, merged