Ewb 2528 update sdk
zepben/pp-translator pull request #19
Opened 2022-11-30 02:55 UTC by Lax125

# Description

Simple dependency update to avoid conflicts in the ewb examples repo.

# Associated tasks:

- [ ] https://github.com/zepben/evolve-sdk-python/pull/116
- [ ] https://github.com/zepben/evolve-sdk-python/pull/115

Tasks this is blocking:
- https://github.com/zepben/ewb-sdk-examples-python/pull/2

# Checklist:

- [ ] I have performed a self review of my own code.
- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.

2022-11-30 02:55 UTC, ryanjcoleman commented
Task linked: [EWB-2528 Update pp_translator](https://app.clickup.com/t/6929263/EWB-2528)

2023-01-02 23:38 UTC, Lax125 commented
No tests needed for SDK version update.

2023-01-03 23:02 UTC, kgreav requested changes
can you update the changelog to say added support for SDK version 0.35.0

2023-01-08 22:58 UTC, kgreav approved these changes

2023-01-08 22:58 UTC, merged